### ISSUE TITLE
csound-repl orchestra evaluation "<leader>eo" doesn't change csound outpt

### ISSUE THREAD

**Issue by paulverone** [kunstmusik/csound-repl#1]
Hello,
I have installed csound-repl plugin for vim in my system. I'm using gentoo and csound6. The audio output is working correctly trough jack. I tried using csound-repl to change the audio output while csound is playing the .csd file but when I change something in the instrument and give the <leader>eo command the sound stays the same. I tried various things, configuring realtime access for users, changing some USE flags but it just doesn't want to work. 
I can't find nothing on the internet so i guess i have to change some system configuration or some package configuration since the issue seems so rare. I understood that the plugin is ment to work out of the box.
Can you help me? Have you ever heard of a similar issue? Thanks

**Comment by kunstmusik** [comment]
I'm not sure I understand, but what I do normally is:

1. Start vim with csound-repl
2. Start a Csound process in a terminal window with `csound someproject.csd --port=10000`
3. Evaluate orchestra code with <leader>eo

For instruments, they should change for new instances of instruments. Older instances will keep running using older code until those instances are turned off.  (This is how Csound deals with new definitions of existing instruments.)

If that doesn't address it, could you provide some more information, perhaps some example code that you started with then what you tried to evaluate?

**Comment by paulverone** [comment]
Hello, 
thank you for the quick reply, sorry if I'm not so clear, I'm really a newbie to csound.
csound_test is the .csd file that I'm using for testing csound.
Usually I open it with vim with the csound-repl plugin *code: vim ~/Music/test.csd 
[csound_test.txt](https://github.com/kunstmusik/csound-repl/files/2684052/csound_test.txt)
Then I start csound *code: csound --port=10000 ~/Music/test.csd
I hear the 440Hz sinusoid and the noise. 
Then I want to change from 440Hz to 180Hz so I edit my test.csd and change instr 1 frequency.
[csound_code_to_evaluate.txt](https://github.com/kunstmusik/csound-repl/files/2684071/csound_code_to_evaluate.txt)

I use <leader>eo, but I still hear 440Hz sinusoid. Shouldn't I hear my new 180Hz sinusoid?
I apologize if I completely misunderstood the usage of your plugin.
Thanks

**Comment by kunstmusik** [comment]
The issue I see is not the plugin but the expectation of change. If you change the definition of an instrument, existing running instances (such as the ones that start from the score section in your project) will not change.  New instances (say if you use the schedule opcode from orchestra code) will use the new definition.

You might take a look at these two videos:

https://www.youtube.com/watch?v=q6GKT5irCBc
https://www.youtube.com/watch?v=CEiUC-E_lL0

For some ideas. If you want to change values for a runtime instrument, you will probably want to use one of Csound's channel opcodes to read/write values.  (Reading in the sounding instrument, writing from control code). The two videos above show live coding of Csound using live.csound.com and orchestra code evaluation.

**Comment by paulverone** [comment]
Thanks for the explanation, I guess I have to study more but you pointed me in the right direction. I saw the videos while waiting for your answer and it's really difficult for me, now, to understand what's going on. 
It's three days that I try to understand why the sound is not changing, feel kind of stupid -.-'
Thanks for helping me out :)

EDIT: got it, more or less.

**Comment by kunstmusik** [comment]
No worries, glad to help. Will close this issue out now. I'd encourage checking out the Csound Users mailing list and Csound Slack channel for help.  Lots of people happy to assist!
