### ISSUE TITLE
Fix instr/endin and opcode/endop detection

### ISSUE THREAD

**Issue by kunstmusik** [kunstmusik/csound-repl#2]
Pete Goodeve reported that instr/endin and opcode/endop detection doesn't work if the keywords are indented in. Makes sense due to regex used in code. 

1. Fix the detection of instr/endin and opcode/endop
2. Update the code to work even if cursor is on the lines with instr/endin/opcode/endop

**Comment by PeteCA** [comment]
This must be some weird bug in vim.  I played around and found that, for instance, just doing `"/^\s*endin`"/ from within an instrument works just as it should, but
 '`:let end = search("^\s*endin")`' fails! 
OTOH something like  '`:let end = search("\s*endin")`' succeeds (though not useful...).

What also works is '`:let end = search("^[ \t]*endin")`', so I guess that would be a workaround.  I've changed the plugin on my machine appropriately.
